Repository YJZero/JS-deep-dive-study, pull requests merged in 2022-12, with the labels that each got.

#2 [10장, 11장 _ 유지영] 객체 리터럴, 원시 값과 객체의 비교
  [10장]객체 리터럴/유지영.md
  [11장] 원시 값과 객체의 비교/유지영.md
Labels: 10장, 11장

#9 [6장, 7장 _ 신나라] 데이터 타입, 연산자
  [6장] 데이터 타입/신나라.md
  [7장] 연산자/신나라.md
Labels: 6장, 7장

#10 [8장, 9장 _ 신동우] 제어문, 타입 변환과 단축 평가
  [8장] 제어문/신동우.md
  [9장] 타입 변환과 단축 평가/신동우.md
Labels: 8장, 9장

#11 [14장, 15장 _ 허지연] 전역 변수의 문제점, let, const 키워드와 블록 레벨 스코프
  [14장] 전역변수의 문제점/허지연.md
  [15장] let, const키워드와 블록 레벨 스코프/허지연.md
Labels: 14장, 15장

#13 [4장, 5장_김순요] 변수, 표현식과 문
  README.md
  [4장]변수/김순요.md
  [5장]표현식_문/김순요.assets/Untitled (1)-16703942410363.png
  [5장]표현식_문/김순요.assets/Untitled (1).png
  [5장]표현식_문/김순요.md
Labels: 4장, 5장

#17 [16장_허지연] 프로퍼티 어트리뷰트
  [16장] 프로퍼티 어트리뷰트/허지연.md
Labels: 16장

#19 [17장_최별] 생성자 함수에 의한 객체 생성
  [17장] 생성자 함수에 의한 객체 생성/17장_최별.pdf
  [17장] 생성자 함수에 의한 객체 생성/최별.md
Labels: 17장

#18 [18장_신나라] 함수와 일급객체
  [18장] 함수와 일급객체/신나라.md
Labels: 18장

#23 [20장]strict mode
  [20장]strict mode/assets/Untitled.png
  [20장]strict mode/김순요.md
Labels: 20장
