Repository YJZero/JS-deep-dive-study, pull requests merged in 2023-01, with the labels that each got.

#28 [21장_허지연] _빌트인 객체
  [21장] 빌트인 객체/허지연.md
Labels: 21장

#27 [22장_신동우] _this
  [22장] this/신동우.md
Labels: 22장

#33 [25장_신나라] 클래스
  [25장] 클래스/신나라.md
Labels: 25장

#34 [24장_김순요] 클로저
  [24장] 클로저/김순요.assets/image-20230103010021607.png
  [24장] 클로저/김순요.assets/image-20230103010110450.png
  [24장] 클로저/김순요.assets/image-20230103010229525.png
  [24장] 클로저/김순요.md
  [4장]변수/김순요.md
  [5장]표현식_문/김순요.assets/Untitled (1)-16703942410363.png
  [5장]표현식_문/김순요.assets/Untitled (1).png
  [5장]표현식_문/김순요.md
Labels: 24장

#35 [26장_유지영] es6 함수의 추가 기능
  [26장] es6 함수의 추가 기능/유지영.md
Labels: 26장

#39 [35장,36장] 스프레드 문법, 디스트럭처링 할당
  [35장] 스프레드 문법/신동우.md
  [36장] 디스트럭처링 할당/신동우.md
Labels: 35장, 36장

#40 [33장_허지연] 7번째 데이터 타입 Symbol
  {33장] 7번째 데이터 타입 Symbol/허지연.md
Labels: 33장

#41 [34장_유지영] 이터러블
  [34장] 이터러블/유지영.md
Labels: 34장

#43 [37장_유지영] Set과 Map
  [37장] Set과 Map/유지영.md
Labels: 37장

#46 [38장_김순요] 브라우저 렌더링
  [38장] 브라우저 렌더링/김순요.pdf
Labels: 38장
