Repository YJZero/JS-deep-dive-study, pull requests merged in 2023-02, with the labels that each got.

#51 [41장, 42장 _ 신동우] 타이머, 비동기 프로그래밍
  [22장] this/신동우.md
  [41장] 타이머/신동우.md
  [42장] 비동기 프로그래밍/신동우.md
  [48장] 모듈/신동우.md
Labels: 41장, 42장

#54 [44장_유지영] REST API
  [44장]REST API/유지영.md
Labels: 44장

#55 [43장_김순요] Ajax
  [43장] Ajax/김순요.md
Labels: 43장
